site_name: My Docs
site_url: https://dsaint31x.github.io/


docs_dir: mkdocs
site_dir: docs

nav:
  - index: index.md
  - samples:
    - sample Page A: sample-a.md

theme: 
  name: 'readthedocs'
  custom_dir: 'custom_theme/'

markdown_extensions:
  - toc:
      permalink: '#'

plugins:
  - search

extra:
  history_buttons: false
  version: v1.3.0
  nav_links:
    - icon: twitter
      icon_type: brand
      text: Siphalor
      url: https://twitter.com/Siphalor
