site_name: My Docs
site_url: https://dsaint31x.github.io/


docs_dir: mkdocs
site_dir: docs

nav:
  - index: usage.md
  - samples:
    - sample Page A: sample-a.md

theme: 
  #name: 'readthedocs'
  name: 'material'
  custom_dir: 'custom_theme/'
