site_name: My Docs
site_url: https://dsaint31x.github.io/


docs_dir: mkdocs
site_dir: docs

plugins:
  - search
    #- mkdocs-simple-hooks:
    #    hooks:
    #      on_pre_build: "mkdocs.hooks:copy_ads"

hooks:
  - hooks.py

nav:
  - index: index.md
  - samples:
    - sample Page A: sample-a.md
  - Git:
    - 'Git/git_setting_ssh.md'
    - 'Git/git_init.md'
  - Python:
    - 'Python/ch00/c00_06_module_package_library.md'

theme: 
  #name: 'readthedocs'
  name: 'material'
  custom_dir: 'custom_theme/'
